// <auto-generated />
using System;
using Domus.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domus.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260704225413_ControleExclusao")]
    partial class ControleExclusao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domus.Domain.Entity.Avaliacao", b =>
                {
                    b.Property<Guid>("Avaliacao_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Contrato_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<Guid>("Imovel_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublicadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("Usuario_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Avaliacao_ID");

                    b.HasIndex("Contrato_ID");

                    b.HasIndex("Imovel_ID");

                    b.HasIndex("Usuario_ID");

                    b.ToTable("Avaliacoes", (string)null);
                });

            modelBuilder.Entity("Domus.Domain.Entity.Chat", b =>
                {
                    b.Property<Guid>("Chat_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Imovel_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Chat_ID");

                    b.HasIndex("Imovel_ID");

                    b.ToTable("Chats", (string)null);
                });

            modelBuilder.Entity("Domus.Domain.Entity.Contrato", b =>
                {
                    b.Property<Guid>("Contrato_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AssinaturaLocador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("AssinaturaLocatario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataTermino")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<Guid>("Imovel_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Locador_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Locatario_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UrlContrato")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Contrato_ID");

                    b.HasIndex("Imovel_ID");

                    b.HasIndex("Locador_ID");

                    b.HasIndex("Locatario_ID");

                    b.ToTable("Contratos", (string)null);
                });

            modelBuilder.Entity("Domus.Domain.Entity.Endereco", b =>
                {
                    b.Property<Guid>("Endereco_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("char(8)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.HasKey("Endereco_ID");

                    b.ToTable("Enderecos", (string)null);
                });

            modelBuilder.Entity("Domus.Domain.Entity.Funcao", b =>
                {
                    b.Property<Guid>("Funcao_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Funcao_ID");

                    b.ToTable("Funcoes", (string)null);

                    b.HasData(
                        new
                        {
                            Funcao_ID = new Guid("11111111-1111-1111-1111-111111111111"),
                            Nome = "Administrador"
                        },
                        new
                        {
                            Funcao_ID = new Guid("22222222-2222-2222-2222-222222222222"),
                            Nome = "Locador"
                        },
                        new
                        {
                            Funcao_ID = new Guid("33333333-3333-3333-3333-333333333333"),
                            Nome = "Locatario"
                        });
                });

            modelBuilder.Entity("Domus.Domain.Entity.ImagemImovel", b =>
                {
                    b.Property<Guid>("ImagemImovel_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Imovel_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UrlImagem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ImagemImovel_ID");

                    b.HasIndex("Imovel_ID");

                    b.ToTable("ImagensImovel", (string)null);
                });

            modelBuilder.Entity("Domus.Domain.Entity.Imovel", b =>
                {
                    b.Property<Guid>("Imovel_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Aprovado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("Avaliado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Banheiros")
                        .HasColumnType("int");

                    b.Property<int>("Comodos")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("Endereco_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MetrosQuadrados")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("Usuario_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorAluguel")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Imovel_ID");

                    b.HasIndex("Endereco_ID")
                        .IsUnique();

                    b.HasIndex("Usuario_ID");

                    b.ToTable("Imoveis", (string)null);
                });

            modelBuilder.Entity("Domus.Domain.Entity.MensagemChat", b =>
                {
                    b.Property<Guid>("MensagemChat_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Chat_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("Usuario_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MensagemChat_ID");

                    b.HasIndex("Chat_ID");

                    b.HasIndex("Usuario_ID");

                    b.ToTable("MensagensChat", (string)null);
                });

            modelBuilder.Entity("Domus.Domain.Entity.MensagemReclamacao", b =>
                {
                    b.Property<Guid>("MensagemReclamacao_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Emissor_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Reclamacao_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.HasKey("MensagemReclamacao_ID");

                    b.HasIndex("Emissor_ID");

                    b.HasIndex("Reclamacao_ID");

                    b.ToTable("MensagensReclamacao", (string)null);
                });

            modelBuilder.Entity("Domus.Domain.Entity.Notificacao", b =>
                {
                    b.Property<Guid>("Notificacao_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("Lida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("Usuario_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Notificacao_ID");

                    b.HasIndex("Usuario_ID");

                    b.ToTable("Notificacoes", (string)null);
                });

            modelBuilder.Entity("Domus.Domain.Entity.ParcelaAluguel", b =>
                {
                    b.Property<Guid>("ParcelaAluguel_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Contrato_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PixCopiaCola")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StatusPagamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlParcelaAluguel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ValorParcela")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ParcelaAluguel_ID");

                    b.HasIndex("Contrato_ID");

                    b.ToTable("ParcelasAluguel", (string)null);
                });

            modelBuilder.Entity("Domus.Domain.Entity.ReciboPagamento", b =>
                {
                    b.Property<Guid>("ReciboPagamento_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataEmissao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("ParcelaAluguel_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlRecibo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("ValorParcela")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ReciboPagamento_ID");

                    b.HasIndex("ParcelaAluguel_ID");

                    b.ToTable("RecibosPagamento", (string)null);
                });

            modelBuilder.Entity("Domus.Domain.Entity.Reclamacao", b =>
                {
                    b.Property<Guid>("Reclamacao_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DataResolucao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("Imovel_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("Usuario_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Reclamacao_ID");

                    b.HasIndex("Imovel_ID");

                    b.HasIndex("Usuario_ID");

                    b.ToTable("Reclamacoes", (string)null);
                });

            modelBuilder.Entity("Domus.Domain.Entity.Usuario", b =>
                {
                    b.Property<Guid>("Usuario_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CPF")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Celular")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EmailAConfirmar")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EmailConfirmado")
                        .HasColumnType("bit");

                    b.Property<Guid?>("Endereco_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("TokenConfirmaEmail")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TokenEmailExpire")
                        .HasColumnType("datetime2");

                    b.HasKey("Usuario_ID");

                    b.HasIndex("CPF")
                        .IsUnique()
                        .HasFilter("[CPF] IS NOT NULL");

                    b.HasIndex("Celular")
                        .IsUnique()
                        .HasFilter("[Celular] IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("EmailAConfirmar")
                        .IsUnique();

                    b.HasIndex("Endereco_ID")
                        .IsUnique()
                        .HasFilter("[Endereco_ID] IS NOT NULL");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Domus.Domain.Entity.UsuarioChat", b =>
                {
                    b.Property<Guid>("UsuarioChat_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Chat_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Usuario_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UsuarioChat_ID");

                    b.HasIndex("Chat_ID");

                    b.HasIndex("Usuario_ID");

                    b.ToTable("UsuarioChat", (string)null);
                });

            modelBuilder.Entity("Domus.Domain.Entity.UsuarioFuncao", b =>
                {
                    b.Property<Guid>("UsuarioFuncao_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("Funcao_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Usuario_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UsuarioFuncao_ID");

                    b.HasIndex("Funcao_ID");

                    b.HasIndex("Usuario_ID");

                    b.ToTable("UsuarioFuncoes", (string)null);
                });

            modelBuilder.Entity("Domus.Domain.Entity.Avaliacao", b =>
                {
                    b.HasOne("Domus.Domain.Entity.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("Contrato_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domus.Domain.Entity.Imovel", "Imovel")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("Imovel_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domus.Domain.Entity.Usuario", "Usuario")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("Usuario_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contrato");

                    b.Navigation("Imovel");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domus.Domain.Entity.Chat", b =>
                {
                    b.HasOne("Domus.Domain.Entity.Imovel", "Imovel")
                        .WithMany("Chats")
                        .HasForeignKey("Imovel_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imovel");
                });

            modelBuilder.Entity("Domus.Domain.Entity.Contrato", b =>
                {
                    b.HasOne("Domus.Domain.Entity.Imovel", "Imovel")
                        .WithMany("Contratos")
                        .HasForeignKey("Imovel_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domus.Domain.Entity.Usuario", "Locador")
                        .WithMany("ContratosComoLocador")
                        .HasForeignKey("Locador_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domus.Domain.Entity.Usuario", "Locatario")
                        .WithMany("ContratosComoLocatario")
                        .HasForeignKey("Locatario_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Imovel");

                    b.Navigation("Locador");

                    b.Navigation("Locatario");
                });

            modelBuilder.Entity("Domus.Domain.Entity.ImagemImovel", b =>
                {
                    b.HasOne("Domus.Domain.Entity.Imovel", "Imovel")
                        .WithMany("Imagens")
                        .HasForeignKey("Imovel_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imovel");
                });

            modelBuilder.Entity("Domus.Domain.Entity.Imovel", b =>
                {
                    b.HasOne("Domus.Domain.Entity.Endereco", "Endereco")
                        .WithOne()
                        .HasForeignKey("Domus.Domain.Entity.Imovel", "Endereco_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domus.Domain.Entity.Usuario", "Usuario")
                        .WithMany("Imoveis")
                        .HasForeignKey("Usuario_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domus.Domain.Entity.MensagemChat", b =>
                {
                    b.HasOne("Domus.Domain.Entity.Chat", "Chat")
                        .WithMany("MensagensChat")
                        .HasForeignKey("Chat_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domus.Domain.Entity.Usuario", "Usuario")
                        .WithMany("MensagensChat")
                        .HasForeignKey("Usuario_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domus.Domain.Entity.MensagemReclamacao", b =>
                {
                    b.HasOne("Domus.Domain.Entity.Usuario", "Emissor")
                        .WithMany("MensagensReclamacao")
                        .HasForeignKey("Emissor_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domus.Domain.Entity.Reclamacao", "Reclamacao")
                        .WithMany("MensagensReclamacao")
                        .HasForeignKey("Reclamacao_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emissor");

                    b.Navigation("Reclamacao");
                });

            modelBuilder.Entity("Domus.Domain.Entity.Notificacao", b =>
                {
                    b.HasOne("Domus.Domain.Entity.Usuario", "Usuario")
                        .WithMany("Notificacoes")
                        .HasForeignKey("Usuario_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domus.Domain.Entity.ParcelaAluguel", b =>
                {
                    b.HasOne("Domus.Domain.Entity.Contrato", "Contrato")
                        .WithMany("ParcelasAluguel")
                        .HasForeignKey("Contrato_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("Domus.Domain.Entity.ReciboPagamento", b =>
                {
                    b.HasOne("Domus.Domain.Entity.ParcelaAluguel", "ParcelaAluguelRecibo")
                        .WithMany("RecibosPagamento")
                        .HasForeignKey("ParcelaAluguel_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParcelaAluguelRecibo");
                });

            modelBuilder.Entity("Domus.Domain.Entity.Reclamacao", b =>
                {
                    b.HasOne("Domus.Domain.Entity.Imovel", "Imovel")
                        .WithMany("Reclamacoes")
                        .HasForeignKey("Imovel_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domus.Domain.Entity.Usuario", "Usuario")
                        .WithMany("Reclamacoes")
                        .HasForeignKey("Usuario_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imovel");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domus.Domain.Entity.Usuario", b =>
                {
                    b.HasOne("Domus.Domain.Entity.Endereco", "EnderecoUsuario")
                        .WithOne()
                        .HasForeignKey("Domus.Domain.Entity.Usuario", "Endereco_ID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EnderecoUsuario");
                });

            modelBuilder.Entity("Domus.Domain.Entity.UsuarioChat", b =>
                {
                    b.HasOne("Domus.Domain.Entity.Chat", "Chat")
                        .WithMany("UsuarioChats")
                        .HasForeignKey("Chat_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domus.Domain.Entity.Usuario", "Usuario")
                        .WithMany("UsuarioChats")
                        .HasForeignKey("Usuario_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domus.Domain.Entity.UsuarioFuncao", b =>
                {
                    b.HasOne("Domus.Domain.Entity.Funcao", "Funcao")
                        .WithMany("UsuarioFuncao")
                        .HasForeignKey("Funcao_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domus.Domain.Entity.Usuario", "Usuario")
                        .WithMany("UsuarioFuncao")
                        .HasForeignKey("Usuario_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domus.Domain.Entity.Chat", b =>
                {
                    b.Navigation("MensagensChat");

                    b.Navigation("UsuarioChats");
                });

            modelBuilder.Entity("Domus.Domain.Entity.Contrato", b =>
                {
                    b.Navigation("ParcelasAluguel");
                });

            modelBuilder.Entity("Domus.Domain.Entity.Funcao", b =>
                {
                    b.Navigation("UsuarioFuncao");
                });

            modelBuilder.Entity("Domus.Domain.Entity.Imovel", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Chats");

                    b.Navigation("Contratos");

                    b.Navigation("Imagens");

                    b.Navigation("Reclamacoes");
                });

            modelBuilder.Entity("Domus.Domain.Entity.ParcelaAluguel", b =>
                {
                    b.Navigation("RecibosPagamento");
                });

            modelBuilder.Entity("Domus.Domain.Entity.Reclamacao", b =>
                {
                    b.Navigation("MensagensReclamacao");
                });

            modelBuilder.Entity("Domus.Domain.Entity.Usuario", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("ContratosComoLocador");

                    b.Navigation("ContratosComoLocatario");

                    b.Navigation("Imoveis");

                    b.Navigation("MensagensChat");

                    b.Navigation("MensagensReclamacao");

                    b.Navigation("Notificacoes");

                    b.Navigation("Reclamacoes");

                    b.Navigation("UsuarioChats");

                    b.Navigation("UsuarioFuncao");
                });
#pragma warning restore 612, 618
        }
    }
}
