@Domus.WebApi_HostAddress = http://localhost:5038/domus

//============================================================
//Controller: LocatarioController
//============================================================
POST {{Domus.WebApi_HostAddress}}/locatario/post/locatario
Content-Type: application/json
{
  "nome": "Locatario",
  "email": "locatario@gmail.com",
  "senha": "123456"
}

###===========================================================


//============================================================
//Controller: LocadorController
//============================================================
POST {{Domus.WebApi_HostAddress}}/locador/post/locador
Content-Type: application/json
{
  "nome": "Locador",
  "email": "locador@gmail.com",
  "senha": "123456"
}

###===========================================================


//============================================================
//Controller: AdminController
//============================================================
POST {{Domus.WebApi_HostAddress}}/admin/post/admin
Content-Type: application/json
{
  "nome": "admin",
  "email": "admin@gmail.com",
  "senha": "123456"
}

###===========================================================


//============================================================
//Controller: ImovelController
//============================================================
POST {{Domus.WebApi_HostAddress}}/imovel/post/imovel
Content-Type: application/json
  {
    "usuario_id": "2967AB27-178C-4A93-9F1F-EFC95052FB61",
    "titulo": "Imovel muito massa",
    "descricao": "Realmente muito massa, e perto (mais ou menos) do São Francisco. Para os mais intimos 'Velho Chico'",
    "comodos": 20,
    "status": 1,
    "valorAluguel": 2500.00,
    "endereco": {
        "cep": "07861140",
        "uf": "AL",
        "cidade": "Delmiro Golveia",
        "bairro": "Campo Grande",
        "rua": "Fernandes Lima",
        "numero": "803",
        "complemento": null
    }  
  }


###===========================================================


//============================================================
//Controller: ContratoController
//============================================================
POST {{Domus.WebApi_HostAddress}}/contrato/post/contrato
Content-Type: application/json
{
  "imovel_id": "C6909269-F0DC-4349-96A5-4582EF534401",
  "titulo": "Contrato de aluguel",
  "descricao": "Contrato de aluguel do imovel muito massa",
  "tipo": "Mensal",
  "urlContrato": "https://www.google.com"
}
###===========================================================

