@Domus.WebApi_HostAddress = http://localhost:5038/domus
@MeuTokenJWT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI0M2RjMDMxOS02YTM2LTQ5OTYtYWMzMC04YTMzOTk5NGIyMmIiLCJ1bmlxdWVfbmFtZSI6IkxvY2Fkb3IiLCJlbWFpbCI6ImxvY2Fkb3JAZ21haWwuY29tIiwicm9sZSI6IkxvY2Fkb3IiLCJuYmYiOjE3ODExODk1ODksImV4cCI6MTc4MTIwMDM4OSwiaWF0IjoxNzgxMTg5NTg5LCJpc3MiOiJkb211cyIsImF1ZCI6ImRvbXVzIn0.Gxpaud7WIsiabjKUSGqiy-GD0KI87oilZ15MG3bg5nU
@Locador_ID = "43dc0319-6a36-4996-ac30-8a339994b22b"
@Locatario_ID = "d162af62-af03-419b-a58a-7f894992bf05"
@Admin_ID = "0caa380d-c1f2-4804-a9bb-6d36b628b519"


//============================================================
//Controller: AuthController
//============================================================
POST {{Domus.WebApi_HostAddress}}/auth/login
Content-Type: application/json

{
  "email": "locador@gmail.com",
  "senha": "123456"
}

###===========================================================



//============================================================
//Controller: LocatarioController
//============================================================
POST {{Domus.WebApi_HostAddress}}/locatario/post/locatario
Content-Type: application/json

{
  "nome": "Locatario2",
  "email": "locatario2@gmail.com",
  "senha": "123456"
}

###===========================================================


//============================================================
//Controller: LocadorController
//============================================================
POST {{Domus.WebApi_HostAddress}}/locador/post/locador
Content-Type: application/json

{
  "nome": "Locador2",
  "email": "locador2@gmail.com",
  "senha": "123456"
}

###===========================================================


//============================================================
//Controller: AdminController
//============================================================
POST {{Domus.WebApi_HostAddress}}/admin/post/admin
Content-Type: application/json

{
  "nome": "admin5",
  "email": "admin5@gmail.com",
  "senha": "123456"
}

###===========================================================


//============================================================
//Controller: ImovelController
//============================================================
POST {{Domus.WebApi_HostAddress}}/imovel/post/imovel
Content-Type: application/json
Authorization: Bearer {{MeuTokenJWT}}

{
  "usuario_id": {{Locador_ID}},
  "titulo": "Lendario Imovel",
  "descricao": "Muitas historias",
  "comodos": 2,
  "status": 1,
  "valorAluguel": 200.00,
  "endereco": {
      "cep": "07861140",
      "uf": "AL",
      "cidade": "Golveia",
      "bairro": "Campo",
      "rua": "Lima",
      "numero": "803",
      "complemento": null
  }  
}


###===========================================================


//============================================================
//Controller: ContratoController
//============================================================
POST {{Domus.WebApi_HostAddress}}/contrato/post/contrato
Content-Type: application/json
Authorization: Bearer {{MeuTokenJWT}}

{
  "imovel_id": "9d2303d6-b48b-4d0a-b727-c51d586049e6",
  "titulo": "Identificador teste",
  "descricao": "Identificador teste Contrato de aluguel do imovel muito massa",
  "tipo": "Mensal",
  "urlContrato": "https://www.google.com////////"
}

###

PUT {{Domus.WebApi_HostAddress}}/contrato/put/assinatura/locador
Content-Type: application/json
Authorization: Bearer {{MeuTokenJWT}}
{
  "locatario_id": {{Locatario_ID}},
  "contrato_id": "5ff33338-028a-48d6-a811-d981f668ba8a"
}

###===========================================================


//============================================================
//Controller: AvaliacaoController
//============================================================
POST {{Domus.WebApi_HostAddress}}/avaliacao/post/avaliacao
Content-Type: application/json
Authorization: Bearer {{MeuTokenJWT}}

{
  "usuario_id": {{Locatario_ID}},
  "imovel_id": "50626A6E-BDD1-43D2-9243-32962DF64219",
  "contrato_id": "08348E82-9659-4648-992B-4C810BF83A5E",
  "titulo": "Avaliação muito massa",
  "descricao": "Descrição da avaliação muito massa",
  "nota": 5
}

###