@Domus.WebApi_HostAddress = http://localhost:5038/domus
@MeuTokenJWT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI0M2RjMDMxOS02YTM2LTQ5OTYtYWMzMC04YTMzOTk5NGIyMmIiLCJ1bmlxdWVfbmFtZSI6IkxvY2Fkb3IiLCJlbWFpbCI6ImxvY2Fkb3JAZ21haWwuY29tIiwicm9sZSI6IkxvY2Fkb3IiLCJuYmYiOjE3ODA2MDk3NzcsImV4cCI6MTc4MDYyMDU3NywiaWF0IjoxNzgwNjA5Nzc3LCJpc3MiOiJkb211cyIsImF1ZCI6ImRvbXVzIn0.sLJ2_QFS0vULtqfWMZpD2N2FBvnKMY2BPdezXP8dmSw


//============================================================
//Controller: AuthController
//============================================================
POST {{Domus.WebApi_HostAddress}}/auth/login
Content-Type: application/json

{
  "email": "locador@gmail.com",
  "senha": "123456"
}

###===========================================================



//============================================================
//Controller: LocatarioController
//============================================================
POST {{Domus.WebApi_HostAddress}}/locatario/post/locatario
Content-Type: application/json

{
  "nome": "Locatario2",
  "email": "locatario2@gmail.com",
  "senha": "123456"
}

###===========================================================


//============================================================
//Controller: LocadorController
//============================================================
POST {{Domus.WebApi_HostAddress}}/locador/post/locador
Content-Type: application/json

{
  "nome": "Locador2",
  "email": "locador2@gmail.com",
  "senha": "123456"
}

###===========================================================


//============================================================
//Controller: AdminController
//============================================================
POST {{Domus.WebApi_HostAddress}}/admin/post/admin
Content-Type: application/json

{
  "nome": "admin2",
  "email": "admin2@gmail.com",
  "senha": "123456"
}

###===========================================================


//============================================================
//Controller: ImovelController
//============================================================
POST {{Domus.WebApi_HostAddress}}/imovel/post/imovel
Content-Type: application/json
Authorization: Bearer {{MeuTokenJWT}}

{
  "usuario_id": "43dc0319-6a36-4996-ac30-8a339994b22b",
  "titulo": "Lendario Imovel",
  "descricao": "Muitas historias",
  "comodos": 2,
  "status": 1,
  "valorAluguel": 200.00,
  "endereco": {
      "cep": "07861140",
      "uf": "AL",
      "cidade": "Golveia",
      "bairro": "Campo",
      "rua": "Lima",
      "numero": "803",
      "complemento": null
  }  
}


###===========================================================


//============================================================
//Controller: ContratoController
//============================================================
POST {{Domus.WebApi_HostAddress}}/contrato/post/contrato
Content-Type: application/json
Authorization: Bearer {{MeuTokenJWT}}

{
  "imovel_id": "C6909269-F0DC-4349-96A5-4582EF534401",
  "titulo": "Contrato de aluguel",
  "descricao": "Contrato de aluguel do imovel muito massa",
  "tipo": "Mensal",
  "urlContrato": "https://www.google.com"
}
###===========================================================

